service: users

provider:
  name: aws
  runtime: nodejs4.3
  region: us-west-2

environment:
  projectId: "photodeck-f6521"
  clientEmail: "firebase-adminsdk-3x9wd@photodeck-f6521.iam.gserviceaccount.com"
  privateKey: <YOUR KEY>

functions:
  userWithPhoneExists:
    handler: handler.userWithPhoneExists
    events:
      - http:
          path: users/exists
          method: get
          integration: lambda-proxy
          cors: true

  userCreate:
    handler: handler.userCreate
    events:
      - http:
          path: users
          method: post
          integration: lambda-proxy
          cors: true

  sendOneTimePass:
    handler: handler.sendOneTimePass
    events:
      - http:
          path: users/send
          method: post
          integration: lambda-proxy
          cors: true

  verifyOneTimePass:
    handler: handler.verifyOneTimePass
    events:
      - http:
          path: users/verify
          method: post
          integration: lambda-proxy
          cors: true
